services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19000:19000" # Metro bundler
      - "19001:19001" # Expo DevTools
      - "19002:19002" # Expo Web
    volumes:
      - .:/screens # Sync your local project with the container
    stdin_open: true
    tty: true
